### ISSUE TITLE
program persistence after unplugging

### ISSUE THREAD

**Issue by cjblocker** [im-tomu/tomu-quickstart#26]
Whenever I unplug my tomu and plug it back in, the program I had loaded on it disappears and I return to the bootloader which blinks between red and green quickly. Is there a way to keep the program I had loaded?
I load the program with:
```bash
$ make
$ dfu-util -D captouch.dfu 
```

I'm on macOS, running `dfu-util -l` before I download the program gives me

```bash 
$ dfu-util -l
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Found Runtime: [05ac:8289] ver=0149, devnum=12, cfg=1, intf=3, path="20-3.3", alt=0, name="UNKNOWN", serial="UNKNOWN"
Found DFU: [1209:70b1] ver=0101, devnum=17, cfg=1, intf=0, path="20-2", alt=0, name="Tomu Bootloader (5) v2.0-rc7", serial="UNKNOWN"
```

**Comment by xobs** [comment]
This is by design.  You must set a flag in your program to automatically boot it.  Once you do this, you will need to use tweezers to flash a new program.

https://github.com/im-tomu/tomu-bootloader#entering-toboot

U2F sets this flag: https://github.com/im-tomu/chopstx/blob/efm32/u2f/platform.c#L47

You would add that flag to the TOBOOT_CONFIGURATION() at https://github.com/im-tomu/tomu-quickstart/blob/master/captouch/main.c#L24:

```c
TOBOOT_CONFIGURATION(TOBOOT_CONFIG_FLAG_AUTORUN);
```
